### ISSUE TITLE
Additional Polymer 1.0 Support

### ISSUE THREAD

**Issue by donny-dont** [AdalbertoLacruz/less_dart#11]
I'm seeing a couple issues around Polymer and less_dart that I'm currently working around.

For `:host` when you give it something like

```
@color: red;
:host {
  .foo {
    color: @color;
  }
}
```

You get

```
:host .foo {
  color: red;
}
```

It seemed like when it was `@host` that it would output the block.

Next one is around mixins

```
:host {
  --my-mixin: {
    color: red;
  };
}
```

This outputs

```
:host --my-mixin: {
  color: red;
}
```

So like above it would need fixing for scoping. But the other thing is that the `;` is actually expected after the mixin. If its not there then Polymer will not handle the style so it appears to be required.

One other gotcha that you could run into is that its actually possible to have a class with a mixin in it.

```
:host {
  --my-toolbar-theme: {
    background-color: green;
    border-radius: 4px;
    border: 1px solid gray;
  };
  --my-toolbar-title-theme: {
    color: green;
  };
}

/* Make only toolbars with the .warning class red and bold */
.warning {
  --my-toolbar-title-theme: {
    color: red;
    font-weight: bold;
  };
}
```

That's from https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins

This one is not something I'm currently doing but appears to be in the specification.

Opening this up to see what we can do here. @AdalbertoLacruz you've been great with cleaning things up for Polymer usage so let me know if this is doable and if you need any help there. I'm not super familiar with the code but I did download it and started giving it a look. So I can possibly help out if need be.

**Comment by AdalbertoLacruz** [comment]
As you know standard less don't support polymer specifics such as @apply and --polymer-mixins, because they are not css standard.

In this context, supporting @apply, let use the --polymer-mixins defined in other polymer components, such as paper-styles. It was a little effort.

Supporting in less_dart the --polymer-mixins definitions is a harder work, spread across many files and a big divergence from the standard (js) implementation.

Also, less has its own mixin system. By example:

```
@color1: red;
@color2: green;
.mymixin() {
    background-color: @color1;
}
:host {
    .mymixin() {
        background-color: @color2;
    }
    .mymixin;
}
h1 {
    .mymixin;
}
```

and you get:

```
:host {
  background-color: green;
}
h1 {
  background-color: red;
}
```

see http://lesscss.org/features/#mixins-feature

Considers the use of less mixins, possibly in this moment is the best relationship effort/result.
